<?php
define('ROOTIMG',"http://localhost/Projet_TDW/public/assets/images/");
define('ROOTCSS',"http://localhost/Projet_TDW/public/assets/css/");
define('ROOTJS',"http://localhost/Projet_TDW/public/assets/js/");
define('ROOTJQUERY',"http://localhost/Projet_TDW/public/assets/js/jquery-3.6.1.min.js");
define('ROOT',"http://localhost/Projet_TDW/public/");
define('USERNAME','root');
define('PASSWORD','');
define('DATABASENAME','tdw');
define('HOSTNAME','localhost');
define('LIEN_CATEGORIES',"http://localhost/Projet_TDW/public/categorie/affiche_page_categorie&categorie=");
define('LIEN_RECETTES',"http://localhost/Projet_TDW/public/recette/affiche_page_recette&id_recette=");
