<?php
define('ROOTIMG',"http://localhost/Projet_TDW/njKMda/assets/images/");
define('ROOTCSS',"http://localhost/Projet_TDW/njKMda/assets/css/");
define('ROOTJS',"http://localhost/Projet_TDW/njKMda/assets/js/");
define('ROOTJQUERY',"http://localhost/Projet_TDW/public/assets/js/jquery-3.6.1.min.js");
define('ROOT',"http://localhost/Projet_TDW/njKMda/");
define('USERNAME','root');
define('PASSWORD','');
define('DATABASENAME','tdw');
define('HOSTNAME','localhost');
define('LIEN_RECETTES',"http://localhost/Projet_TDW/public/recette/affiche_page_recette&id_recette=");
define('LIEN_NEWS',"http://localhost/Projet_TDW/public/news/affiche_page_new&id_news=");
